### PR TITLE
perform 1 git commit per recipe (instead of a giant one).

### PR DESCRIPTION
**Pull request by alainravet**
smaller commits document better the action of each recipe.

### CODE REVIEW

**Comment by alainravet** [comment]
example of what it produces : 
example

**Comment by drnic** [comment]
This is a neat idea! I'll try to play with it soon before merging.

**Comment by drnic** [comment]
@alainravet my new thinking is to reject this (boo!!) as it adds complexity for the sake of novelty (which I normally love). Do you think breaking the scrolls into smaller commits is an important feature?

**Comment by alainravet** [comment]
Yes, I think it's really VERY important to give each scroll its individual commit.

As individual/tiny commits show you clearly what each scroll does, you can (more) easily see :
- what the problem is if for some reason 2 scrolls don't work well together (wrong order, 1 scroll undid what a previous one had done, incompatible additions, etc..),
- that you forgot to include 1 scroll (no commit)
- where/how to improve 1 scroll, if it does not exactly what you expect/need.
- ..

Also :
- 'git blame' will give you valuable information : "this line was added/modified for this reason by this scroll."
- for education purpose, you can learn and understand what a scroll has to do to make its magic just by reading 1 compact commit
- for documentation purpose : 1 huge nameless glob vs n smaller and well-named tiny commits.

Without this feature, people have no way to understand what happened: 1 huge commit created dozens of files

I didn't implement it here but I usually go 1 step further and regroup commits in 1 "loop" to better show they are part of 1 action; 
gitloop
src: https://github.com/alainravet/gitloop#readme

**Comment by jeremyf** [comment]
:+1: I concur with @alainravet … @drnic can we get a merge?

**Pull request merged**
