### PR TITLE
RailsAdmin

### PR DESCRIPTION
**Pull request by sferik**
Added an official RailsAdmin scroll. :memo:

Also, cleaned up `appscrolls.gemspec` in separate commits, in case you want to cherry-pick.

### CODE REVIEW

**Comment by drnic** [comment]
Thanks for the clean up.

I'll test out the rails_admin scroll soon. I can't remember why it wasn't in the original release.

Is there a password/protection that could be generated for it? E.g. resque scroll?

**Comment by drnic** [comment]
Why do you want users to use your git repo instead of gem releases? This will make bundler slower for ever and ever as it checks the git repo for commits, I think.

**Comment by sferik** [comment]
Rails Admin has not yet been released as a gem. It's high on the priority list, but there are a few things I'd like to clean up first. If using the git repo is a deal breaker, I can move it even higher.

**Comment by sferik** [comment]
For password protection, we recommend Devise. Is there a scroll for that yet?

**Comment by drnic** [comment]
No, I haven't pushed out an auth solution yet.

I just checked active_admin and it doesn't auto-setup protection either. So two things:
1. I suck.
2. Let's do the auto-authentication for these two admin dashboards later.

Need to educate people well that they need to protect these dashboards from people who might guess the endpoints and have admin access :)

**Comment by drnic** [comment]
Thanks to @heliostatic for also creating a version of this Scroll

**Comment by heliostatic** [comment]
Happy to be a dupe of @sferik on this one. Thanks to @drnic for AppScrolls.

**Pull request merged**
